# fly.toml app configuration file generated for fed-funds-probability on 2023-08-21T15:15:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fed-funds-probability"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
