# fly.toml app configuration file generated for fed-funds-probability on 2023-08-21T13:39:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fed-funds-probability"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
